version: 2
jobs:
  test:
    docker:
    - image: circleci/php:7.2-stretch
    steps:
    - checkout
    - run: composer validate --no-interaction --strict
    - run: composer install --no-interaction
    - run: vendor/bin/phpcs -p src/
    - run: php -d memory_limit=1G vendor/bin/phpstan analyze
workflows:
  version: 2
  workflow:
    jobs:
    - test:
        filters:
          branches:
            only:
            - master
