version: 2
jobs:
  test:
    docker:
    - image: circleci/php:7.2-stretch
    steps:
    - checkout
    - run: composer validate --no-interaction --strict
    - run: composer install --no-interaction
    - run: composer test --no-interaction
workflows:
  version: 2
  workflow:
    jobs:
    - test:
        filters:
          branches:
            only:
            - master
