version: 2.1
jobs:
  test:
    docker:
    - image: circleci/php:7.3-stretch
    steps:
    - checkout
    - run: composer validate --no-interaction --strict
    - run: composer install --no-interaction
    - run: composer outdated --no-interaction --direct
    - run: composer syntax
    - run: composer style
    - run: php -d memory_limit=1G vendor/bin/phpstan analyze
workflows:
  version: 2
  workflow:
    jobs:
    - test:
        filters:
          branches:
            only:
            - master
